/*
 * Created on 2025-09-27 ( 14:25:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;

import java.io.Serializable;


import jakarta.persistence.*;

/**
 * JPA entity class for "Service"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="service", schema="public", catalog="memoire_database" )
public class Service implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idservice", nullable=false)
    private int        idservice ;

    @Column(name="nom", length=254)
    private String     nom ;

    @Column(name="description", length=254)
    private String     description ;

    @OneToOne
    @JoinColumn(name="idcategorie", referencedColumnName="idcategorie")
    Categorie categorie;



    /**
     * Constructor
     */
    public Service() {
		super();
    }
    
    public void setIdservice( int idservice ) {
        this.idservice = idservice ;
    }
    public int getIdservice() {
        return this.idservice;
    }


    public void setNom( String nom ) {
        this.nom = nom ;
    }
    public String getNom() {
        return this.nom;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public Categorie getCategorie() {
        return categorie;
    }

    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }



    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Service[");
		sb.append("idservice=").append(idservice);
		sb.append(separator).append("nom=").append(nom);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
