/*
 * Created on 2025-09-27 ( 14:25:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "Contrat"
 *
 * @author Telosys
 *
 */
public class ContratResponseDTO implements Serializable {

    private static final long serialVersionUID = 1L;


    //--- OTHER DATA FIELDS
    private int idcontrat;
    private String horaires ;
    private String jours ;
    private BigDecimal montantSalaire ;
    private Integer duree ;
    private String type_contrat;
    private String statut;

    /**
     * Constructor
     */
    public ContratResponseDTO() {
		super();
    }
    


    public void setHoraires( String horaires ) {
        this.horaires = horaires ;
    }
    public String getHoraires() {
        return this.horaires;
    }

    public void setJours( String jours ) {
        this.jours = jours ;
    }
    public String getJours() {
        return this.jours;
    }

    public void setMontantSalaire( BigDecimal montantSalaire ) {
        this.montantSalaire = montantSalaire ;
    }
    public BigDecimal getMontantSalaire() {
        return this.montantSalaire;
    }

    public void setDuree( Integer duree ) {
        this.duree = duree ;
    }
    public Integer getDuree() {
        return this.duree;
    }


    public int getIdcontrat() {
        return idcontrat;
    }

    public void setIdcontrat(int idcontrat) {
        this.idcontrat = idcontrat;
    }

    public String getType_contrat() {
        return type_contrat;
    }

    public void setType_contrat(String type_contrat) {
        this.type_contrat = type_contrat;
    }

    public String getStatut() {
        return statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }
}
