/*
 * Created on 2025-09-27 ( 14:25:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.request;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.*;

import java.io.Serializable;
import java.util.Date;

/**
 * DTO class for "Prestataire"
 *
 * @author Telosys
 *
 */
public class PrestataireRequestDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    @NotBlank(message = "Le nom doit etre renseigner")
    @Size(min=2,message="Le nom doit etre au moins 2 caracteres")
    private String nom ;

    @NotBlank(message = "Le prenom doit etre renseigner")
    @Size(min = 4,message="Le prenom doit etre au moins de 6 caracteres")
    private String prenom ;

    @Min(value = 700000000,message = "Le numero de telephone est invalide")
    @Digits(integer = 9,fraction = 0,message="Le numero de telephone est invalide")
    private Long telephone ;

    @NotBlank(message = "Le mail doit être renseigné")
    @Email(message = "email invalide")
    private String email ;

    @NotBlank(message = "L'adresse doit etre renseigner")
    @Size(min=4,message = "l'adresse doit etre au moins de 6 caracteres")
    private String adresse ;

    @NotBlank(message = "Le mot de passe doit etre renseigner")
    @Size(min=8,message = "Le mot doit etre au moins de 8 caracteres")
    private String motdepasse ;

    @JsonFormat(pattern = "yyyy-MM-dd")
    @NotNull(message = "La date de naissance doit etre renseigner")
    @Past(message = "La date de naissance doit etre dans le passe")
    private Date date_de_naissance;


    /**
     * Constructor
     */
    public PrestataireRequestDTO() {
		super();
    }


    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public Long getTelephone() {
        return telephone;
    }

    public void setTelephone(Long telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getMotdepasse() {
        return motdepasse;
    }

    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }

    public Date getDate_de_naissance() {
        return date_de_naissance;
    }

    public void setDate_de_naissance(Date date_de_naissance) {
        this.date_de_naissance = date_de_naissance;
    }
}
